from prov.model import ProvDocument, Namespace, PROV

ENTITY = Namespace('entity', 'http://entity.example.org/')
INTENTION = Namespace('intention', 'http://intention.example.org/')
INTERACTION = Namespace('interaction', 'http://interaction.example.org/')
CAPABILITY = Namespace('capability', 'http://capability.example.org/')
WF_EXECUTION = Namespace('wf_execution', 'http://wf_execution.example.org/')
TASK_EXECUTION = Namespace('task_execution', 'http://task_execution.example.org/')
PROVMA = Namespace('', 'http://prov_multi_agent.example.org/')


doc = ProvDocument()
doc.add_namespace(PROV)
doc.add_namespace(ENTITY)
doc.add_namespace(INTENTION)
doc.add_namespace(INTERACTION)
doc.add_namespace(CAPABILITY)
doc.add_namespace(WF_EXECUTION)
doc.add_namespace(TASK_EXECUTION)
doc.add_namespace(PROVMA)

agent = doc.agent(PROVMA["Agent"])
system = doc.agent(PROVMA["System"])
user = doc.agent(PROVMA["User"])
tool = doc.entity(PROVMA["Tool"])
intention = doc.entity(PROVMA["Intention"])
workflow_definition = doc.entity(PROVMA["WorkflowDefinition"])
interaction = doc.activity(PROVMA["Interaction"])
task_execution = doc.activity(PROVMA["TaskExecution"])

doc.used(task_execution, workflow_definition)
doc.wasGeneratedBy(workflow_definition, interaction)
doc.used(interaction, intention)
doc.wasInformedBy(interaction, interaction)
doc.wasInformedBy(task_execution, interaction)
doc.wasInformedBy(task_execution, task_execution)
doc.used(interaction, tool)
doc.wasAssociatedWith(interaction, system)
doc.wasAssociatedWith(interaction, agent)
doc.wasAssociatedWith(interaction, user)
doc.wasAssociatedWith(task_execution, system)
doc.wasAssociatedWith(task_execution, agent)
doc.wasAssociatedWith(task_execution, user)
doc.used(task_execution, tool)
doc.wasAttributedTo(intention, agent)
doc.actedOnBehalfOf(agent, agent)
doc.wasAttributedTo(tool, agent)

from prov.dot import prov_to_dot
dot = prov_to_dot(doc, direction="LR")
dot.set_ratio("compress")
dot.set_ranksep("0.1")
dot.set_nodesep("0.1")
dot.write_pdf("provenance_model.pdf")
dot.write_png("provenance_model.png")
